// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/github_auth_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/github_auth_interface.go -destination=internal/mocks/github_auth_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	github "github.com/google/go-github/v57/github"
	githubv4 "github.com/shurcooL/githubv4"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubAuthService is a mock of GitHubAuthService interface.
type MockGitHubAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubAuthServiceMockRecorder
	isgomock struct{}
}

// MockGitHubAuthServiceMockRecorder is the mock recorder for MockGitHubAuthService.
type MockGitHubAuthServiceMockRecorder struct {
	mock *MockGitHubAuthService
}

// NewMockGitHubAuthService creates a new mock instance.
func NewMockGitHubAuthService(ctrl *gomock.Controller) *MockGitHubAuthService {
	mock := &MockGitHubAuthService{ctrl: ctrl}
	mock.recorder = &MockGitHubAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubAuthService) EXPECT() *MockGitHubAuthServiceMockRecorder {
	return m.recorder
}

// CreateGitHubClient mocks base method.
func (m *MockGitHubAuthService) CreateGitHubClient(ctx context.Context, userUUID, provider string) (*github.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGitHubClient", ctx, userUUID, provider)
	ret0, _ := ret[0].(*github.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGitHubClient indicates an expected call of CreateGitHubClient.
func (mr *MockGitHubAuthServiceMockRecorder) CreateGitHubClient(ctx, userUUID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGitHubClient", reflect.TypeOf((*MockGitHubAuthService)(nil).CreateGitHubClient), ctx, userUUID, provider)
}

// CreateGraphqlClient mocks base method.
func (m *MockGitHubAuthService) CreateGraphqlClient(ctx context.Context, userUUID, provider string) (*githubv4.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGraphqlClient", ctx, userUUID, provider)
	ret0, _ := ret[0].(*githubv4.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGraphqlClient indicates an expected call of CreateGraphqlClient.
func (mr *MockGitHubAuthServiceMockRecorder) CreateGraphqlClient(ctx, userUUID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGraphqlClient", reflect.TypeOf((*MockGitHubAuthService)(nil).CreateGraphqlClient), ctx, userUUID, provider)
}

// GetAllProviders mocks base method.
func (m *MockGitHubAuthService) GetAllProviders() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProviders")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetAllProviders indicates an expected call of GetAllProviders.
func (mr *MockGitHubAuthServiceMockRecorder) GetAllProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProviders", reflect.TypeOf((*MockGitHubAuthService)(nil).GetAllProviders))
}

// GetGitHubAccessToken mocks base method.
func (m *MockGitHubAuthService) GetGitHubAccessToken(userUUID, provider string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitHubAccessToken", userUUID, provider)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitHubAccessToken indicates an expected call of GetGitHubAccessToken.
func (mr *MockGitHubAuthServiceMockRecorder) GetGitHubAccessToken(userUUID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitHubAccessToken", reflect.TypeOf((*MockGitHubAuthService)(nil).GetGitHubAccessToken), userUUID, provider)
}
