import React, { useState, useEffect } from 'react';
import { Plus } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { 
  useFoundationModels, 
  useCreateConfiguration, 
  useCreateDeployment,
  FoundationModel 
} from '@/services/aiPlatformApi';
import { ModelSearchStep } from './ModelSearchStep';
import { DeploymentConfigurationStep } from './DeploymentConfigurationStep';
import { CreateDeploymentDialogButtons } from './CreateDeploymentDialogButtons';

interface CreateDeploymentDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedTeam?: string; // Current team from parent context
  availableTeams?: string[]; // Available teams for selection
}

export const CreateDeploymentDialog: React.FC<CreateDeploymentDialogProps> = ({ 
  open, 
  onOpenChange,
  selectedTeam,
  availableTeams = []
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedModel, setSelectedModel] = useState<FoundationModel | null>(null);
  const [selectedVersion, setSelectedVersion] = useState('');
  const [step, setStep] = useState<'select' | 'configure'>('select');
  const [dialogSelectedTeam, setDialogSelectedTeam] = useState<string>('');

  // Set default team when dialog opens or selectedTeam changes
  useEffect(() => {
    if (open && selectedTeam && selectedTeam !== 'all') {
      setDialogSelectedTeam(selectedTeam);
    } else if (open) {
      setDialogSelectedTeam('');
    }
  }, [open, selectedTeam]);

  const { toast } = useToast();
  const { data: modelsData, isLoading: modelsLoading } = useFoundationModels();
  const createConfiguration = useCreateConfiguration();
  const createDeployment = useCreateDeployment();

  const models = modelsData?.resources || [];
  const filteredModels = models.filter(model =>
    searchTerm === '' || 
    (model.displayName && model.displayName.toLowerCase().includes(searchTerm.toLowerCase())) ||
    (model.model && model.model.toLowerCase().includes(searchTerm.toLowerCase())) ||
    (model.provider && model.provider.toLowerCase().includes(searchTerm.toLowerCase())) ||
    (model.description && model.description.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  const handleModelSelect = (model: FoundationModel) => {
    // Find the correct scenarioId based on executableId from allowedScenarios
    const allowedScenario = model.allowedScenarios?.find(
      scenario => scenario.executableId === model.executableId
    );
    
    // Create a new model object with the correct scenarioId
    const modelWithScenarioId = {
      ...model,
      scenarioId: allowedScenario?.scenarioId || model.scenarioId
    };
    
    setSelectedModel(modelWithScenarioId);
    // Set the latest version as default
    const latestVersion = model?.versions?.find(v => v.isLatest);
    if (latestVersion) {
      setSelectedVersion(latestVersion.name);
    }
    setStep('configure');
  };

  const handleBack = () => {
    setStep('select');
    setSelectedModel(null);
    setSelectedVersion('');
  };

  const handleDeploy = async () => {
    if (!selectedModel) return;

    // Determine the team to use
    const teamToUse = dialogSelectedTeam || selectedTeam;
    
    // Validate team selection when teams are available
    if (availableTeams.length > 0 && !teamToUse) {
      toast({
        title: "Team Required",
        description: "Please select a team before deploying",
        variant: "destructive",
      });
      return;
    }

    try {
      await createDeployment.mutateAsync({
        configurationRequest: {
          executableId: selectedModel.executableId,
          name: `${selectedModel.model}-autogenerated`,
          parameterBindings: [
            { key: 'modelName', value: selectedModel.model },
            { key: 'modelVersion', value: selectedVersion }
          ],
          scenarioId: selectedModel.scenarioId,
        },
        // Include team when teams are available and we have a valid team
        ...(availableTeams.length > 0 && teamToUse && { team: teamToUse })
      });

      toast({
        title: "Deployment Created",
        description: `${selectedModel.displayName} deployment has been initiated`,
      });

      // Reset and close dialog
      setStep('select');
      setSelectedModel(null);
      setSearchTerm('');
      setSelectedVersion('');
      onOpenChange(false);
    } catch (error) {
      toast({
        title: "Deployment Failed",
        description: error instanceof Error ? error.message : "Failed to create deployment",
        variant: "destructive",
      });
    }
  };

  const isDeploying = createConfiguration.isPending || createDeployment.isPending;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl h-[80vh] max-h-[80vh] flex flex-col">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-100 rounded-lg">
              <Plus className="h-5 w-5 text-blue-600" />
            </div>
            <div>
              <DialogTitle>
                {step === 'select' ? 'Deploy AI Model' : `Deploy ${selectedModel?.displayName}`}
              </DialogTitle>
              <DialogDescription>
                {step === 'select' 
                  ? 'Choose an AI model to deploy from the available foundation models'
                  : 'Configure deployment settings for your selected model'
                }
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        {/* Team Selection Dropdown - Positioned outside DialogHeader */}
        {availableTeams.length > 0 && (
          <div className="flex items-center gap-2">
            <Label htmlFor="team-select" className="text-sm font-medium text-muted-foreground">
              Team:
            </Label>
            <Select
              value={dialogSelectedTeam}
              onValueChange={setDialogSelectedTeam}
            >
                <SelectTrigger id="team-select" className={`w-64 h-10 ${!dialogSelectedTeam ? 'border-red-500 focus:border-red-500' : ''}`}>
                <SelectValue placeholder="Select team" />
              </SelectTrigger>
              <SelectContent>
                {availableTeams.map((team) => (
                  <SelectItem key={team} value={team}>
                    {team}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}

        <div className="flex-1 overflow-hidden">
          {step === 'select' && (
            <ModelSearchStep
              searchTerm={searchTerm}
              onSearchChange={setSearchTerm}
              models={models}
              filteredModels={filteredModels}
              isLoading={modelsLoading}
              onModelSelect={handleModelSelect}
            />
          )}

          {step === 'configure' && selectedModel && (
            <DeploymentConfigurationStep
              selectedModel={selectedModel}
              selectedVersion={selectedVersion}
              onVersionChange={setSelectedVersion}
            />
          )}
        </div>

        <DialogFooter className="flex-row justify-between">
          <CreateDeploymentDialogButtons
            step={step}
            isDeploying={isDeploying}
            selectedModel={selectedModel}
            hasTeamSelected={availableTeams.length === 0 || !!dialogSelectedTeam}
            onBack={handleBack}
            onCancel={() => onOpenChange(false)}
            onDeploy={handleDeploy}
          />
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
